//! Stage 2. Drop the noise, sort by how much changed, cut one chunk per file.
//!
//! One chunk is one file, always: two small files are never packed together,
//! and only a file that does not fit on its own is cut again along its hunk
//! boundaries.

use globset::{Glob, GlobSet, GlobSetBuilder};
use serde::{Deserialize, Serialize};

use crate::budget::{estimate_ascii_tokens, estimate_tokens};
use crate::config::{Config, ConfigError, Model, PROMPT_SKELETON_TOKENS, TriageSettings};
use crate::domain::{ChangeSet, DEV_NULL, FileChange};
use crate::security::PathPolicy;
use crate::tool::Registry;

use super::{StageContext, StageError};

pub const NUMBER: u8 = 2;
pub const NAME: &str = "triage";

/// Slack on top of the character based token estimate, which is conservative
/// but not exact. One reserve for the whole formula rather than a fudge
/// factor hidden in each term.
const HEADROOM_TOKENS: u32 = 1_024;

/// Below this a chunk cannot hold a file header, one hunk and the lines the
/// model has to quote back as evidence, so every real file would fail as too
/// large. A config that leaves less than this is wrong, not merely tight.
const MIN_CHUNK_TOKENS: u32 = 2_000;

/// Markers a generator leaves behind. Both spellings are conventions, not
/// standards, so they are matched anywhere in the file's diff text.
const GENERATED_MARKERS: [&str; 2] = ["@generated", "Code generated by"];

/// One chunk is one file, or one piece of a file too big to fit in a single
/// turn. Two files are never packed together, however small.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub struct Chunk {
    pub index: usize,
    pub path: String,
    /// Which piece of its file this is, counting from zero, and how many
    /// pieces that file was cut into. `pieces == 1` is the ordinary case.
    /// Both are needed downstream: the pieces of one file must not share a
    /// `trace_id`, and a model reading piece three has to be told the earlier
    /// hunks exist rather than concluding they do not.
    #[serde(default)]
    pub piece: usize,
    #[serde(default = "one_piece")]
    pub pieces: usize,
    pub diff: String,
}

impl Chunk {
    /// True when this file was cut, so the model is looking at part of it.
    pub fn is_split(&self) -> bool {
        self.pieces > 1
    }
}

fn one_piece() -> usize {
    1
}

/// A file that will not be reviewed, and why. Goes into the report.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub struct SkippedFile {
    pub path: String,
    pub reason: String,
}

#[derive(Clone, Debug, Default, Deserialize, PartialEq, Serialize)]
pub struct TriagePlan {
    pub chunks: Vec<Chunk>,
    pub skipped: Vec<SkippedFile>,
}

/// How many tokens of diff one chunk may carry.
///
/// The hard ceiling is whatever still fits in the window:
///
/// `context_window_tokens − max_output_tokens − prompt skeleton − tool allowance − headroom`
///
/// The working size is `[triage].max_chunk_tokens`, clamped down to that
/// ceiling. It has no builtin default: the leftover window is not itself a
/// useful review turn, and how much diff is worth one call depends on the
/// model and the project.
#[derive(Clone, Copy, Debug)]
pub struct ChunkLimit {
    tokens: u32,
}

impl ChunkLimit {
    /// `prompt_tokens` is measured from the assembled instructions and the
    /// tool schemas, not guessed: `PROMPT_SKELETON_TOKENS` is only the floor
    /// the startup check uses, before there is a registry to measure. It
    /// still floors this, so a prompt that somehow measures smaller than the
    /// startup check assumed cannot buy back window the check already gave
    /// away.
    pub fn new(
        model: &Model,
        config: &Config,
        tools: &Registry,
        prompt_tokens: u32,
    ) -> Result<Self, ConfigError> {
        let allowance = Self::tool_allowance(config, tools);
        let reserved = model
            .max_output_tokens
            .saturating_add(prompt_tokens.max(PROMPT_SKELETON_TOKENS))
            .saturating_add(allowance)
            .saturating_add(HEADROOM_TOKENS);
        let fit = model.context_window_tokens.saturating_sub(reserved);
        // The allowance is the one term a config can raise without noticing
        // what it costs: rounds times output bytes grows fast enough to eat a
        // small window whole. Say so here, where the registry is known, rather
        // than letting every file fail as too large.
        if allowance > 0 && fit < MIN_CHUNK_TOKENS {
            return Err(ConfigError::ToolAllowanceTooLarge {
                model: model.name.clone(),
                context_window_tokens: model.context_window_tokens,
                rounds: config.review.max_tool_rounds,
                allowance,
                left: fit,
            });
        }
        Ok(Self {
            tokens: fit.min(config.triage.max_chunk_tokens),
        })
    }

    pub fn tokens(self) -> u32 {
        self.tokens
    }

    /// What the tool loop may append to `input` before the last round.
    /// Delivery-only tools do not grow the conversation with bulk output, so
    /// they do not reserve this. Neither does one this run's worktree cannot
    /// answer: it is offered to the model like the rest, but all it can ever
    /// return is a one-line refusal.
    fn tool_allowance(config: &Config, tools: &Registry) -> u32 {
        let investigates = tools
            .offered_on(crate::tool::Round::Investigation)
            .iter()
            .any(|tool| {
                tool.purpose() != crate::tool::Purpose::Delivery && tool.unavailable().is_none()
            });
        if !investigates {
            return 0;
        }
        estimate_ascii_tokens(config.review.max_tool_output_bytes)
            .saturating_mul(config.review.max_tool_rounds)
    }
}

/// The skip rules, built once per run. `deny_paths` is not in here: that one
/// is `security`'s hard boundary, and this type only owns the cost policy.
pub struct FileFilter {
    skip_paths: GlobSet,
    skip_generated: bool,
    skip_files_over_bytes: u64,
}

impl FileFilter {
    pub fn new(triage: &TriageSettings) -> Result<Self, ConfigError> {
        let mut builder = GlobSetBuilder::new();
        for pattern in &triage.skip_paths {
            builder.add(
                Glob::new(pattern).map_err(|error| ConfigError::InvalidGlob {
                    field: "[triage].skip_paths",
                    pattern: pattern.clone(),
                    reason: error.to_string(),
                })?,
            );
        }
        Ok(Self {
            skip_paths: builder.build().map_err(|error| ConfigError::InvalidGlob {
                field: "[triage].skip_paths",
                pattern: String::new(),
                reason: error.to_string(),
            })?,
            skip_generated: triage.skip_generated,
            skip_files_over_bytes: triage.skip_files_over_bytes,
        })
    }

    /// Why this file is not reviewed, or `None` when it is. `deny_paths`
    /// comes first: it is the one rule the config cannot take away, and a
    /// file that lands on it is skipped even though the diff carries it.
    pub fn reason(&self, file: &FileChange, paths: &PathPolicy) -> Option<String> {
        let diff = FileDiff::new(file);
        if paths.is_denied(&file.new_path) || paths.is_denied(&file.old_path) {
            return Some("denied by deny_paths".to_string());
        }
        if self.skip_paths.is_match(&file.new_path) {
            return Some("matches [triage].skip_paths".to_string());
        }
        if file.binary {
            return Some("binary".to_string());
        }
        if file.new_path == DEV_NULL {
            return Some("the whole file was deleted".to_string());
        }
        if file.hunks.is_empty() {
            return Some("no reviewable lines in the diff".to_string());
        }
        if self.skip_generated && diff.contains_any(&GENERATED_MARKERS) {
            return Some("generated".to_string());
        }
        let size = diff.new_side_bytes();
        if size > self.skip_files_over_bytes {
            return Some(format!(
                "larger than [triage].skip_files_over_bytes ({size} > {})",
                self.skip_files_over_bytes
            ));
        }
        None
    }
}

/// One file's diff, rebuilt from the change set. Every piece it hands out is
/// a unified diff fragment of its own, headers included, so a later stage
/// still knows which file it is looking at.
struct FileDiff<'a> {
    file: &'a FileChange,
}

impl<'a> FileDiff<'a> {
    fn new(file: &'a FileChange) -> Self {
        Self { file }
    }

    fn header(&self) -> String {
        format!(
            "--- {}\n+++ {}\n",
            Self::side("a", &self.file.old_path),
            Self::side("b", &self.file.new_path)
        )
    }

    fn side(prefix: &str, path: &str) -> String {
        match path {
            DEV_NULL => DEV_NULL.to_string(),
            path => format!("{prefix}/{path}"),
        }
    }

    /// The path a report should name. A deleted file has no new side, so it
    /// is named by the one it had.
    fn display_path(&self) -> String {
        match self.file.new_path.as_str() {
            DEV_NULL | "" => self.file.old_path.clone(),
            path => path.to_string(),
        }
    }

    fn whole(&self) -> String {
        let mut text = self.header();
        for hunk in &self.file.hunks {
            text.push_str(&hunk.text);
        }
        text
    }

    fn contains_any(&self, markers: &[&str]) -> bool {
        self.file
            .hunks
            .iter()
            .any(|hunk| markers.iter().any(|marker| hunk.text.contains(marker)))
    }

    /// The new file's size as far as the diff shows it: the lines that
    /// survive on the new side, which are the added and context ones.
    fn new_side_bytes(&self) -> u64 {
        self.file
            .hunks
            .iter()
            .flat_map(|hunk| hunk.text.lines())
            .filter(|line| line.starts_with('+') || line.starts_with(' '))
            .map(|line| line.len() as u64)
            .sum()
    }

    /// One piece while the file fits, otherwise as few pieces as the hunk
    /// boundaries allow. A single hunk over the limit still gets a piece to
    /// itself: cutting inside a hunk would hand the model a broken diff.
    fn pieces(&self, limit: u32) -> Vec<String> {
        let whole = self.whole();
        if estimate_tokens(&whole) <= limit {
            return vec![whole];
        }
        let header = self.header();
        let header_tokens = estimate_tokens(&header);
        let mut pieces = Vec::new();
        let mut body = String::new();
        let mut tokens = header_tokens;
        for hunk in &self.file.hunks {
            let cost = estimate_tokens(&hunk.text);
            if !body.is_empty() && tokens.saturating_add(cost) > limit {
                pieces.push(format!("{header}{body}"));
                body.clear();
                tokens = header_tokens;
            }
            body.push_str(&hunk.text);
            tokens = tokens.saturating_add(cost);
        }
        if !body.is_empty() {
            pieces.push(format!("{header}{body}"));
        }
        pieces
    }
}

pub struct Triage;

impl Triage {
    pub fn run(
        context: &mut StageContext<'_>,
        changeset: &ChangeSet,
        prompt_tokens: u32,
    ) -> Result<TriagePlan, StageError> {
        let model = context.settings.selection()?.model;
        let limit = ChunkLimit::new(
            model,
            &context.settings.config,
            &context.adapters.tools,
            prompt_tokens,
        )?;
        let filter = FileFilter::new(&context.settings.config.triage)?;
        let plan = Self::plan(changeset, &filter, context.paths, limit);

        for file in &plan.skipped {
            tracing::debug!(path = %file.path, reason = %file.reason, "file skipped");
        }
        tracing::info!(
            chunks = plan.chunks.len(),
            skipped = plan.skipped.len(),
            chunk_limit = limit.tokens(),
            prompt_tokens,
            "triage done"
        );
        context.complete(NUMBER, NAME, &plan)?;
        Ok(plan)
    }

    /// Filter, sort, cut. Everything it needs is in the arguments, so the
    /// algorithm is testable without a run directory or a model.
    fn plan(
        changeset: &ChangeSet,
        filter: &FileFilter,
        paths: &PathPolicy,
        limit: ChunkLimit,
    ) -> TriagePlan {
        let mut skipped = Vec::new();
        let mut reviewable: Vec<&FileChange> = Vec::new();
        for file in &changeset.files {
            match filter.reason(file, paths) {
                Some(reason) => skipped.push(SkippedFile {
                    path: FileDiff::new(file).display_path(),
                    reason,
                }),
                None => reviewable.push(file),
            }
        }

        // Most changed lines first. No path weighting: which directory is
        // worth more is a project policy, and `skip_paths` is where a user
        // says so. The path tie break only makes the order reproducible.
        reviewable.sort_by(|left, right| {
            right
                .changed_lines
                .len()
                .cmp(&left.changed_lines.len())
                .then_with(|| left.new_path.cmp(&right.new_path))
        });

        let mut chunks = Vec::new();
        for file in reviewable {
            let cut = FileDiff::new(file).pieces(limit.tokens());
            let pieces = cut.len();
            for (piece, diff) in cut.into_iter().enumerate() {
                chunks.push(Chunk {
                    index: chunks.len(),
                    path: file.new_path.clone(),
                    piece,
                    pieces,
                    diff,
                });
            }
        }
        TriagePlan { chunks, skipped }
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;
    use std::path::{Path, PathBuf};

    /// The fakes below are about the loop, not about arguments, so they share
    /// one declaration: a single path, which is all any of them reads.
    fn one_path() -> &'static Signature {
        static SIGNATURE: std::sync::OnceLock<Signature> = std::sync::OnceLock::new();
        SIGNATURE.get_or_init(|| {
            Signature::new(vec![crate::tool::Parameter::optional(
                "path",
                crate::tool::Shape::Path,
                "the file to look at",
            )])
        })
    }

    use crate::config::SecuritySettings;
    use crate::domain::Hunk;
    use crate::tool::{Purpose, Round, Signature, Tool, ToolError, ToolOutput};

    use super::*;

    /// The working size every sizing test measures against. Config has no
    /// builtin default for it, so the fixture names it.
    const WORKING_SIZE: u32 = 20_000;

    const CONFIG: &str = r#"
[review]
max_tool_rounds = 12
max_files_per_listing = 200
max_hits_per_search = 50
max_file_bytes = 262144
max_tool_output_bytes = 32768

[triage]
max_chunk_tokens = 20000
skip_files_over_bytes = 262144

[security]
allow_extensions = ["c", "h", "rs"]

[[provider]]
name = "deepseek"
protocol = "openai"
base_url = "https://api.deepseek.com"
api_key = "DEEPSEEK_API_KEY"
currency = "CNY"
budget_per_run = 10.0

[[model]]
name = "small"
default = true
provider = "deepseek"
input_per_1m_tokens = 2.0
output_per_1m_tokens = 3.0
context_window_tokens = 32768
max_output_tokens = 4096

[[model]]
name = "large"
provider = "deepseek"
input_per_1m_tokens = 4.0
output_per_1m_tokens = 12.0
context_window_tokens = 131072
max_output_tokens = 4096
"#;

    struct Echo;

    impl Tool for Echo {
        fn name(&self) -> &str {
            "echo"
        }

        fn description(&self) -> &str {
            "returns its argument"
        }

        fn signature(&self) -> &Signature {
            one_path()
        }

        fn purpose(&self) -> Purpose {
            Purpose::Content
        }

        fn rounds(&self) -> &'static [Round] {
            &[Round::Investigation]
        }

        fn execute(&self, _arguments: &serde_json::Value) -> Result<ToolOutput, ToolError> {
            Ok(ToolOutput::new(String::new()))
        }
    }

    fn config(text: &str) -> Config {
        toml::from_str(text).expect("valid toml")
    }

    fn model<'a>(config: &'a Config, name: &str) -> &'a Model {
        config.select_model(Some(name)).expect("model").model
    }

    fn registry(with_tool: bool) -> Registry {
        let mut registry = Registry::new();
        if with_tool {
            registry.register(Box::new(Echo));
        }
        registry
    }

    fn policy(deny: &[&str]) -> PathPolicy {
        let settings = SecuritySettings {
            deny_paths: deny.iter().map(|pattern| pattern.to_string()).collect(),
            ..SecuritySettings::for_tests()
        };
        PathPolicy::new(
            &settings,
            &[PathBuf::from("/repo/.reviewbot/runs")],
            Some(Path::new("/repo")),
        )
        .expect("valid globs")
    }

    /// A file with `count` hunks of `added` added lines each, numbered so the
    /// two line sets stay believable.
    fn file(path: &str, hunks: usize, added: u32) -> FileChange {
        let mut change = FileChange {
            old_path: path.to_string(),
            new_path: path.to_string(),
            hunks: Vec::new(),
            commentable_lines: BTreeSet::new(),
            changed_lines: BTreeSet::new(),
            binary: false,
        };
        for index in 0..hunks {
            let start = 1 + index as u32 * 100;
            let mut text = format!("@@ -{start},1 +{start},{} @@\n", added + 1);
            for offset in 0..added {
                let line = start + offset;
                text.push_str(&format!("+int added_{line}(void);\n"));
                change.commentable_lines.insert(line);
                change.changed_lines.insert(line);
            }
            text.push_str(" int tail(void);\n");
            change.commentable_lines.insert(start + added);
            change.hunks.push(Hunk {
                old_start: start,
                old_count: 1,
                new_start: start,
                new_count: added + 1,
                text,
            });
        }
        change
    }

    fn changeset(files: Vec<FileChange>) -> ChangeSet {
        ChangeSet {
            files,
            ..ChangeSet::default()
        }
    }

    fn plan(files: Vec<FileChange>, limit: u32) -> TriagePlan {
        let settings = TriageSettings::for_tests();
        Triage::plan(
            &changeset(files),
            &FileFilter::new(&settings).expect("valid globs"),
            &policy(&[]),
            ChunkLimit { tokens: limit },
        )
    }

    #[test]
    fn two_small_files_stay_two_chunks() {
        let plan = plan(
            vec![file("src/one.c", 1, 2), file("src/two.c", 1, 3)],
            10_000,
        );
        assert_eq!(plan.chunks.len(), 2, "never packed together");
        assert_eq!(
            plan.chunks[0].path, "src/two.c",
            "three changed lines sort ahead of two"
        );
        assert_eq!(plan.chunks[1].path, "src/one.c");
        for chunk in &plan.chunks {
            assert!(chunk.diff.starts_with("--- a/"), "{}", chunk.diff);
            assert_eq!(
                chunk.diff.matches("+++ ").count(),
                1,
                "one file per chunk: {}",
                chunk.diff
            );
        }
    }

    #[test]
    fn a_file_over_the_limit_is_cut_along_its_hunks_and_the_others_are_not() {
        let plan = plan(
            vec![file("src/big.c", 8, 20), file("src/small.c", 1, 1)],
            200,
        );
        let big: Vec<&Chunk> = plan
            .chunks
            .iter()
            .filter(|chunk| chunk.path == "src/big.c")
            .collect();
        let small: Vec<&Chunk> = plan
            .chunks
            .iter()
            .filter(|chunk| chunk.path == "src/small.c")
            .collect();
        assert!(big.len() > 1, "the big file was cut: {}", big.len());
        assert_eq!(small.len(), 1, "the small file is untouched");
        for chunk in big {
            assert!(chunk.diff.starts_with("--- a/src/big.c\n+++ b/src/big.c\n"));
            assert!(chunk.diff.contains("@@ "), "every piece carries a hunk");
        }
        let indexes: Vec<usize> = plan.chunks.iter().map(|chunk| chunk.index).collect();
        assert_eq!(indexes, (0..plan.chunks.len()).collect::<Vec<_>>());
    }

    #[test]
    fn one_hunk_is_never_cut_in_half_however_small_the_limit() {
        let plan = plan(vec![file("src/big.c", 3, 40)], 0);
        assert_eq!(plan.chunks.len(), 3, "one piece per hunk, no further");
    }

    #[test]
    fn every_skip_rule_names_its_reason_and_yields_no_chunk() {
        let mut binary = file("doc/logo.png", 1, 1);
        binary.binary = true;

        let mut deleted = file("src/gone.c", 1, 1);
        deleted.new_path = DEV_NULL.to_string();

        let mut generated = file("src/api.pb.c", 1, 1);
        generated.hunks[0]
            .text
            .push_str("+// @generated by protoc\n");

        let big = file("src/huge.c", 40, 4);

        let settings = TriageSettings {
            skip_paths: vec!["vendor/**".to_string()],
            skip_files_over_bytes: 1_024,
            ..TriageSettings::for_tests()
        };
        let files = vec![
            file("vendor/lib.c", 1, 1),
            binary,
            deleted,
            generated,
            big,
            file(".reviewbot/runs/abc/report.md", 1, 1),
            file("src/kept.c", 1, 1),
        ];
        let plan = Triage::plan(
            &changeset(files),
            &FileFilter::new(&settings).expect("valid globs"),
            &policy(&["secrets/**"]),
            ChunkLimit { tokens: 10_000 },
        );

        let reasons: Vec<(&str, &str)> = plan
            .skipped
            .iter()
            .map(|file| (file.path.as_str(), file.reason.as_str()))
            .collect();
        assert_eq!(reasons.len(), 6, "{reasons:?}");
        assert!(
            reasons
                .iter()
                .any(|(path, reason)| *path == "vendor/lib.c" && reason.contains("skip_paths"))
        );
        assert!(
            reasons
                .iter()
                .any(|(path, reason)| *path == "doc/logo.png" && *reason == "binary")
        );
        assert!(reasons.iter().any(
            |(path, reason)| *path == "src/gone.c" && reason.contains("whole file was deleted")
        ));
        assert!(
            reasons
                .iter()
                .any(|(path, reason)| *path == "src/api.pb.c" && *reason == "generated")
        );
        assert!(reasons.iter().any(
            |(path, reason)| *path == "src/huge.c" && reason.contains("skip_files_over_bytes")
        ));
        assert!(
            reasons
                .iter()
                .any(|(path, reason)| path.starts_with(".reviewbot/runs")
                    && reason.contains("deny_paths")),
            "the runs directory is denied even when the diff carries it: {reasons:?}"
        );

        assert_eq!(plan.chunks.len(), 1);
        assert_eq!(plan.chunks[0].path, "src/kept.c");
    }

    fn limit(model: &Model, config: &Config, tools: &Registry) -> ChunkLimit {
        ChunkLimit::new(model, config, tools, PROMPT_SKELETON_TOKENS)
            .expect("the window has room for the diff")
    }

    /// `max_chunk_tokens` as written, for any model with room for it. The
    /// window is a ceiling, not the working size.
    #[test]
    fn the_working_size_is_the_one_the_config_asked_for() {
        let config = config(CONFIG);
        let small = limit(model(&config, "small"), &config, &registry(false));
        let large = limit(model(&config, "large"), &config, &registry(false));
        assert_eq!(small.tokens(), WORKING_SIZE);
        assert_eq!(large.tokens(), WORKING_SIZE);
    }

    #[test]
    fn the_hard_ceiling_follows_the_model() {
        let config =
            config(&CONFIG.replace("max_chunk_tokens = 20000", "max_chunk_tokens = 1000000"));
        let small = limit(model(&config, "small"), &config, &registry(false));
        let large = limit(model(&config, "large"), &config, &registry(false));
        assert!(
            large.tokens() > small.tokens(),
            "{} vs {}",
            large.tokens(),
            small.tokens()
        );
        assert_eq!(
            small.tokens(),
            32_768 - 4_096 - PROMPT_SKELETON_TOKENS - HEADROOM_TOKENS
        );
    }

    /// The reservation follows the prompt that is actually going out. A
    /// measurement under the startup floor does not shrink it: that window
    /// was spoken for when the model was let through.
    #[test]
    fn a_bigger_measured_prompt_shrinks_the_limit_and_a_smaller_one_does_not() {
        // A working size out of the way, so what is measured here is the
        // window arithmetic rather than the clamp.
        let config =
            config(&CONFIG.replace("max_chunk_tokens = 20000", "max_chunk_tokens = 1000000"));
        let model = model(&config, "small");
        let tools = registry(false);

        let floor = ChunkLimit::new(model, &config, &tools, PROMPT_SKELETON_TOKENS)
            .expect("room for the diff");
        let measured = ChunkLimit::new(model, &config, &tools, PROMPT_SKELETON_TOKENS + 8_000)
            .expect("room for the diff");
        assert_eq!(
            measured.tokens(),
            floor.tokens() - 8_000,
            "a prompt 8000 tokens bigger takes 8000 tokens off the diff"
        );

        let understated = ChunkLimit::new(model, &config, &tools, 1).expect("room for the diff");
        assert_eq!(
            understated.tokens(),
            floor.tokens(),
            "measuring under the floor does not buy back window the startup check spent"
        );
    }

    #[test]
    fn a_window_too_tight_for_the_working_size_uses_what_fits() {
        let text = CONFIG.replace(
            "context_window_tokens = 32768",
            "context_window_tokens = 20000",
        );
        let config = config(&text);
        let tight = limit(model(&config, "small"), &config, &registry(false));
        let fit = 20_000 - 4_096 - PROMPT_SKELETON_TOKENS - HEADROOM_TOKENS;
        assert!(fit < WORKING_SIZE, "{fit}");
        assert_eq!(tight.tokens(), fit);
    }

    #[test]
    fn registered_tools_and_more_rounds_shrink_the_limit() {
        // A small per-round cap and a working size out of the way, so the
        // round count can be varied over a wide range and still be what the
        // arithmetic turns on. The shape of the formula is the subject here,
        // not the shipped numbers.
        let roomy = CONFIG
            .replace("max_chunk_tokens = 20000", "max_chunk_tokens = 1000000")
            .replace(
                "max_tool_output_bytes = 32768",
                "max_tool_output_bytes = 4096",
            );
        let plain = config(&roomy);
        let large = model(&plain, "large");
        let without = limit(large, &plain, &registry(false));
        let with = limit(large, &plain, &registry(true));
        assert!(
            with.tokens() < without.tokens(),
            "a registered tool reserves room in the loop"
        );

        let busier = config(&roomy.replace("max_tool_rounds = 12", "max_tool_rounds = 40"));
        let busier_limit = limit(model(&busier, "large"), &busier, &registry(true));
        assert!(
            busier_limit.tokens() < with.tokens(),
            "more rounds reserve more"
        );

        let no_tools = limit(model(&busier, "large"), &busier, &registry(false));
        assert_eq!(
            no_tools.tokens(),
            without.tokens(),
            "with no tool registered the rounds cost nothing"
        );
    }

    /// The reserve is the one term a config can inflate without seeing the
    /// bill. Left alone it turns every file into `ChunkTooLarge` one model
    /// call at a time; the run should refuse to start instead.
    #[test]
    fn a_reserve_that_eats_the_window_is_refused_rather_than_paid_for() {
        let greedy = config(&CONFIG.replace("max_tool_rounds = 12", "max_tool_rounds = 400"));
        let error = ChunkLimit::new(
            model(&greedy, "large"),
            &greedy,
            &registry(true),
            PROMPT_SKELETON_TOKENS,
        )
        .expect_err("the reserve does not fit");
        assert!(
            matches!(
                error,
                ConfigError::ToolAllowanceTooLarge { rounds: 400, .. }
            ),
            "{error:?}"
        );
        // With nothing to spend the rounds on, the same config is fine.
        limit(model(&greedy, "large"), &greedy, &registry(false));
    }

    #[test]
    fn max_chunk_tokens_is_clamped_to_what_still_fits() {
        let smaller =
            config(&CONFIG.replace("max_chunk_tokens = 20000", "max_chunk_tokens = 1000"));
        let clamped = limit(model(&smaller, "large"), &smaller, &registry(false));
        assert_eq!(clamped.tokens(), 1_000);

        let bigger =
            config(&CONFIG.replace("max_chunk_tokens = 20000", "max_chunk_tokens = 1000000"));
        let raised = limit(model(&bigger, "large"), &bigger, &registry(false));
        assert_eq!(
            raised.tokens(),
            131_072 - 4_096 - PROMPT_SKELETON_TOKENS - HEADROOM_TOKENS,
            "it can exceed the 24k default but not the window leftover"
        );
    }
}
